version: "3"

services:
  kdc:
    build:
      context: .
      target: kdc # use "kdc" image from Dockerfile.
    container_name: kdc
    hostname: kdc
    volumes:
      - ./kdc:/kdc
    tty: true # equivalent: docker run -t

  alice:
    build:
      context: .
      target: client
    container_name: alice
    hostname: alice
    volumes:
      - ./client:/client
    tty: true

  bob:
    build:
      context: .
      target: client
    container_name: bob
    hostname: bob
    volumes:
      - ./client:/client
    tty: true
