version: "3"

services:
  kdc:
    build: ./kdc
    container_name: kdc
    volumes:
      - ./kdc/kdc:/code/kdc
    tty: true

  alice:
    build: ./client
    container_name: alice
    volumes:
      - ./client/client:/code/client
      - ${LOG_DIR}:/var/log
    tty: true

  bob:
    build: ./client
    container_name: bob
    volumes:
      - ./client/client:/code/client
      - ${LOG_DIR}:/var/log
    tty: true
