version: "3"

services:
  kdc:
    build: ./kdc
    container_name: kdc
    volumes:
      - ./kdc:/code/kdc
      - ./crypto:/code/crypto
      - ${LOG_DIR}:/var/log
    tty: true

  alice:
    build: ./client
    container_name: alice
    volumes:
      - ./client:/code/client
      - ./crypto:/code/crypto
      - ${LOG_DIR}:/var/log
    tty: true

  bob:
    build: ./client
    container_name: bob
    volumes:
      - ./client:/code/client
      - ./crypto:/code/crypto
      - ${LOG_DIR}:/var/log
    tty: true
